# Generated by Django 3.0.6 on 2021-06-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='approve',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
