# Generated by Django 3.0.6 on 2021-06-23 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travello', '0004_book_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='did',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travello.destination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
