# Generated by Django 3.0.6 on 2021-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20210623_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='approve',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
